### ISSUE TITLE
Empty juno.xml in branch 3.6.0

### ISSUE THREAD

**Issue by taiji76** [OP-TEE/manifest#142]
Hi,

I tried to build OP-TEE 3.6.0 with the below command on the Juno board, but I couldn't.

```
repo init -u https://github.com/OP-TEE/manifest.git -m juno.xml -b 3.6.0
```
The error message is like the below.
```
fatal: manifest 'juno.xml' not available
fatal: error parsing manifest /home/taiji/work/tz/rkp/juno/.repo/manifests/juno.xml: no element found: line 1, column 0
```

So that I checked the juno.xml file of the branch 3.6.0 and noticed this file is empty.
Please check this file.

Sungjin.

**Comment by jforissier** [comment]
Hi @taiji76,

You're right, something wrong happened when we created the 3.6.0 branch/tag. Perhaps a bug in `make_stable.sh`. I'll take a look.
In the meantime, you can checkout `juno.xml` from the master branch and manually update optee* and build to 3.6.0.

**Comment by taiji76** [comment]
I got it. 
Thanks a lot!

Sungjin

**Comment by jforissier** [comment]
https://github.com/OP-TEE/manifest/pull/143 for a proper fix of 3.6.0.

There is definitely something wrong with `make_stable.sh` because as I ran it again, another file was left empty (`hikey.xml` IIRC).

**Comment by jbech-linaro** [comment]
> There is definitely something wrong with `make_stable.sh` because as I ran it again, another file was left empty (`hikey.xml` IIRC).

This is the issue I was mumbling about when doing the 3.5.0 release. I experienced none deterministic behavior. Let's see if we can update it for the 3.7.0 release.

**Comment by jbech-linaro** [comment]
Since #143 has been merged, I'm closing this.
