### ISSUE TITLE
QEMUv8: linux link error: 'relocation truncated to fit'

### ISSUE THREAD

**Issue by jforissier** [OP-TEE/manifest#150]
Building `qemu_v8.xml` from scratch, I get:
```
$ make linux
...
  MODPOST vmlinux.o
/home/jerome/work/optee_repo_qemu_v8/build/../toolchains/aarch64/bin/aarch64-linux-gnu-ld: arch/arm64/kernel/head.o: in function `__primary_switched':
/home/jerome/work/optee_repo_qemu_v8/linux/arch/arm64/kernel/head.S:457: undefined reference to `kaslr_early_init'
/home/jerome/work/optee_repo_qemu_v8/linux/arch/arm64/kernel/head.S:457:(.init.text+0x398): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `kaslr_early_init'
make[1]: *** [Makefile:1029: vmlinux] Error 1
```

I've never seen this before... Is anyone else having this problem, or is something wrong in my build environment?

**Comment by jforissier** [comment]
> or is something wrong in my build environment?

That must be it, because I could build with no error on another laptop. Sorry for the noise, I'll post my findings when I understand what happened.

**Comment by jbech-linaro** [comment]
Yes, tried it here also, I saw no issues.

**Comment by jforissier** [comment]
@jbech-linaro thanks for trying. I have cleaned my cache (`ccache -C`), and now all is good. I wonder if it may be related to my switching version of `ccache` while investigating https://github.com/OP-TEE/optee_os/issues/3378. Anyways, I guess there is no point in keeping this issue open.

**Comment by jbech-linaro** [comment]
> it may be related to my switching version of `ccache` while investigating [OP-TEE/optee_os#3378](https://github.com/OP-TEE/optee_os/issues/3378).

I saw that you mentioned it. It's actually the first time ever I see an issue with ccache and I've been using it for more than 10 years. So I have really good faith in ccache otherwise.

**Comment by Brucefang** [comment]
> @jbech-linaro thanks for trying. I have cleaned my cache (`ccache -C`), and now all is good. I wonder if it may be related to my switching version of `ccache` while investigating [OP-TEE/optee_os#3378](https://github.com/OP-TEE/optee_os/issues/3378). Anyways, I guess there is no point in keeping this issue open.

may I ask how do you clean your cache?

**Comment by jbech-linaro** [comment]
Two ways, one is in the response you replied to, i.e. `ccache -C`, or alternatively run `ccache -s -v` and you'll see where you ccache directory is located. i.e., you'll see something like this:
```
  Cache directory:                /home/jyx/.cache/ccache
```
Then simply just rm -rf that folder.
