### ISSUE TITLE
ManifestInvalidPathError:

### ISSUE THREAD

**Issue by da1234cao** [OP-TEE/manifest#157]
**error**.ManifestInvalidPathError: <linkfile> invalid "src": ../toolchains/aarch64/bin/aarch64-linux-gnu-gdb: bad component: .. 
The environment is Ubuntu 18.04 and the Prerequisites are already installed. 
$ repo init -u https://github.com/OP-TEE/manifest.git -m qemu_v8.xml -b 3.3.0

**Comment by da1234cao** [comment]
Before,I successfully installed  optee 3.6 ,qemu 。for the reason of test [fuzzer](https://github.com/Riscure/optee_fuzzer)，I want to try qemu_v8 -b 3.3.0 。However,in the `repo init` step ,it tells a error

**Comment by da1234cao** [comment]
Traceback (most recent call last):
  File "/home/dacao/exercise/optee_v8/.repo/repo/main.py", line 622, in <module>
    _Main(sys.argv[1:])
  File "/home/dacao/exercise/optee_v8/.repo/repo/main.py", line 596, in _Main
    result = run()
  File "/home/dacao/exercise/optee_v8/.repo/repo/main.py", line 589, in <lambda>
    run = lambda: repo._Run(name, gopts, argv) or 0
  File "/home/dacao/exercise/optee_v8/.repo/repo/main.py", line 266, in _Run
    result = cmd.Execute(copts, cargs)
  File "/home/dacao/exercise/optee_v8/.repo/repo/subcmds/init.py", line 498, in Execute
    self._LinkManifest(opt.manifest_name)
  File "/home/dacao/exercise/optee_v8/.repo/repo/subcmds/init.py", line 339, in _LinkManifest
    self.manifest.Link(name)
  File "/home/dacao/exercise/optee_v8/.repo/repo/manifest_xml.py", line 192, in Link
    self.Override(name)
  File "/home/dacao/exercise/optee_v8/.repo/repo/manifest_xml.py", line 185, in Override
    self._Load()
  File "/home/dacao/exercise/optee_v8/.repo/repo/manifest_xml.py", line 510, in _Load
    self._ParseManifest(nodes)
  File "/home/dacao/exercise/optee_v8/.repo/repo/manifest_xml.py", line 618, in _ParseManifest
    project = self._ParseProject(node)
  File "/home/dacao/exercise/optee_v8/.repo/repo/manifest_xml.py", line 942, in _ParseProject
    self._ParseLinkFile(project, n)
  File "/home/dacao/exercise/optee_v8/.repo/repo/manifest_xml.py", line 1096, in _ParseLinkFile
    self._ValidateFilePaths('linkfile', src, dest)
  File "/home/dacao/exercise/optee_v8/.repo/repo/manifest_xml.py", line 1077, in _ValidateFilePaths
    '<%s> invalid "src": %s: %s' % (element, src, msg))
error.ManifestInvalidPathError: <linkfile> invalid "src": ../toolchains/aarch64/bin/aarch64-linux-gnu-gdb: bad component: ..

**Comment by jbech-linaro** [comment]
What version of repo are you using? There are two things that have happened that breaks either old builds or new builds. Python 2.x is legacy and Python 3.x is the what is needed. Because of that you need to either use old "repo" (v1.x) which is using Python 2 a new repo (v2.x) which is using Python 3. Your error message is because of wrong combination of repo, python and OP-TEE. It'd be great if we could've done something about it, but we can't, the only thing we can fix is most recent version. We cannot force Linux distro's and Google to downgrade their tools (so people can successfully clone and work with old OP-TEE version). So, unfortunately people have to roll op their sleeves when trying to use old OP-TEE versions.

Summary: For old OP-TEE versions like ~3.6 and older, use repo 1.x + Python2, for OP-TEE 3.7 and higher use repo 2.x + Python 3.x.

Then we the other error, pycryptodome. If you stumble upon that, please search GitHub issues in optee_os and build. There are many threads about that (with solutions).

**Comment by liyangzmx** [comment]
I encountered the same problem on the **3.8.0** branch, but I found that there is no `<linkfile src = "../ toolchains / aarch32 / bin / arm-linux-gnueabihf-gdb"dest =" build / gdb "/>` in `manifests/default.xml` on the latest **master** branch

Then execute `repo sync` normally.

In the end, I manually created this link after `make -f toolchains.mk`:
`ln -s toolchains/aarch32/bin/arm-linux-gnueabihf-gdb build/gdb`

**Comment by da1234cao** [comment]
* I use repo2.x + python3.7(conda). Not successful.
* About skiping the error,It is not a good way. Because, `raise error`  break the  `repo init` in half.

**Question how to use the repo 1.x? **
* Although  I clone the [repo-git](https://android.googlesource.com/tools/repo.git/+/refs/tags/v1.13.8)，then `reset --hard`  back to version 1.13.8.
* However ,  Everytime I  use `repo init` ,the repo will automatic  update to the repo 2.x. 
* How do I prevent　the  repo 1.x change to repo 2.x ?

For the reason,I dont Familiar with build process.I need the repo function.

**Comment by jbech-linaro** [comment]
I've tried both QEMU v7 and v8. v7 works fine (see v7 log), however on v8 I get the same error message as you (one link to gdb and the other doesn't). By going into `.repo/repo` and checking out an older version, re-run init, then things work. I.e., the below here is working, when you need to check out an older version.

```bash
$ repo init -u https://github.com/OP-TEE/manifest.git -m qemu_v8.xml -b 3.3.0 --reference /media/jbech/TSHB_LINUX/devel/optee_projects/reference
$ cd .repo/repo/
$ git checkout v1.13.11 
$ cd -
$ repo init -m qemu_v8.xml -b 3.3.0 --reference /media/jbech/TSHB_LINUX/devel/optee_projects/reference
$ repo sync -j3
$ cd build && git lg
* 53119b7 - (grafted, HEAD, tag: 3.3.0, tag: m/3.3.0) Use GCC 8 (1 year, 5 months ago) <Jerome Forissier>
``` 

--- 
# QEMU v7 log

```bash
[jbech@goby /media/jbech/TSHB_LINUX/devel/optee_projects/test] 
$ repo init -u https://github.com/OP-TEE/manifest.git -m default.xml -b 3.3.0 --reference /media/jbech/TSHB_LINUX/devel/optee_projects/reference
Downloading Repo source from https://gerrit.googlesource.com/git-repo
remote: Counting objects: 2, done
remote: Finding sources: 100% (48/48)
remote: Total 48 (delta 25), reused 48 (delta 25)
Unpacking objects: 100% (48/48), done.
From https://gerrit.googlesource.com/git-repo
   d38300c..910dfe8  master     -> origin/master
   0b57eed..d957ec6  stable     -> origin/stable
 * [new tag]         v2.4       -> v2.4
 * [new tag]         v2.4.1     -> v2.4.1
Downloading manifest from https://github.com/OP-TEE/manifest.git

Your identity is: Joakim Bech <xxxyyyzzz@linaro.org>
If you want to change this, please re-run 'repo init' with --config-name

repo has been initialized in /media/jbech/TSHB_LINUX/devel/optee_projects/test
[jbech@goby /media/jbech/TSHB_LINUX/devel/optee_projects/test] 
$ repo sync -j4
Fetching projects: 100% (13/13), done.               
Checking out files: 100% (61007/61007), done.buildroot.gitChecking out files:  35% (21809/61007)   
Checking out projects: 100% (13/13), done.               
repo sync has finished successfully.
[jbech@goby /media/jbech/TSHB_LINUX/devel/optee_projects/test] 
$ python --version
Python 2.7.16
[jbech@goby /media/jbech/TSHB_LINUX/devel/optee_projects/test] 
$ repo --version
repo version v2.4.1
       (from https://gerrit.googlesource.com/git-repo)
repo launcher version 2.4
       (from /home/jbech/bin/repo)
       (currently at 2.4.1)
repo User-Agent git-repo/2.4.1 (Linux) git/2.20.1 Python/3.7.3
git 2.20.1
git User-Agent git/2.20.1 (Linux) git-repo/2.4.1
Python 3.7.3 (default, Dec 20 2019, 18:57:59) 
[GCC 8.3.0]
[jbech@goby /media/jbech/TSHB_LINUX/devel/optee_projects/test] 
$ cd build && git lg
* 53119b7 - (grafted, HEAD, tag: 3.3.0, tag: m/3.3.0) Use GCC 8 (1 year, 5 months ago) <Jerome Forissier>
```
