### ISSUE TITLE
trusted-firmware-a.git is no longer available

### ISSUE THREAD

**Issue by norrathep** [OP-TEE/manifest#207]
It looks like https://github.com/TF-A/trusted-firmware-a no longer works. 
And all XML files seem to depend on it. 
Can we just ignore this repo?

**Comment by vchong** [comment]
We've moved to https://git.trustedfirmware.org/TF-A/trusted-firmware-a.git/ quite some time ago. Are you using an old copy of the repo?

**Comment by norrathep** [comment]
Ah, sorry I misread the error message. It seems to be due to the invalid certificate from trusted-firmware-a. 
It works now after I disabled the SSL check.
