### ISSUE TITLE
QUESTION: OP-TEE Version in the Manifest?

### ISSUE THREAD

**Issue by nathan-menhorn** [OP-TEE/manifest#256]
Is there any reason that the OP-TEE version cannot be specified in the manifest? It appears all of the XML manifest pull the latest OP-TEE version. However, there are some issues with some devices, e.g. Versal, when pulling from the latest version instead of using the latest supported version. Is there maybe a flag that can be passed in to specify the OP-TEE version or could the manifest be updated? Thank you.

@jenswi-linaro 
@ldts

**Comment by jenswi-linaro** [comment]
Try checking out the branch (-b `4.0.0`) instead of the tag `4.0.0` whatever you're checking out with repo.

**Comment by nathan-menhorn** [comment]
Thank you!
