### ISSUE TITLE
versal broken

### ISSUE THREAD

**Issue by ldts** [OP-TEE/manifest#271]
For legal reasons, we had to remove the tree that hosted TF-A for Versal. I am working on setting up a new one.

**Comment by ldts** [comment]
I was just notified today of this change

**Comment by ldts** [comment]
@jforissier would it be ok if I point the tree to my github while I work with AMD/Xilinx on getting a branch on their github?

**Comment by jforissier** [comment]
> @jforissier would it be ok if I point the tree to my github while I work with AMD/Xilinx on getting a branch on their github?

Fine with me.

**Comment by ldts** [comment]
#272
