### ISSUE TITLE
Is the target "FVP" not supported anymore?

### ISSUE THREAD

**Issue by targetnull** [OP-TEE/manifest#5]
I just followed the instructions in [README](https://github.com/OP-TEE/manifest) but it returned a 403 status code as I run `repo sync`, saying 
>error: The requested URL returned error: 403 while accessing https://github.com/linaro-swg/bios_qemu_tz_arm.git.git/info/refs. 

When I try to acceess it directly in the browser, I get **GitHub.com no longer supports git over dumb**.

I have viewed the `fvp.xml` and `default.xml` already, but I didn't make any modification. Actually I have no idea how to modify it, they seem normal, just `path` and `name` without the `refs` mentioned in the error info.

Has anyone run it successfully?
Thanks in advance.

==============================================

It seems that they have typed an unnecessary `.git` in the `name` attribution. I deleted those `.git`s and it finally started to receive.

However, the access to busybox failed, saying **The remote end hung up unexpectedly**, maybe something wrong with my network?

**Comment by pascal-brand-st-dev** [comment]
I confirm FVP is still supported. I tested it yesterday, using https://github.com/OP-TEE/manifest/blob/master/README.md#tips-and-tricks, and everything was fine.

About busybox, the following standalone command should work fine. If not, you should check your network / proxy settings before using the manifest:

    git clone git://busybox.net/busybox.git

**Comment by targetnull** [comment]
Hi, Brand.
Did you modify the `fvp.xml` file before you run it? Looks like that it will add an `.git` extension in the path automatically when I run repo, so I have to delete those `.git` characters in the `path` attribution manually, and  I mean every `path` attribution. That seems a little weird.

**Comment by vchong** [comment]
Look at the original xml files on github. There is no .git extension in any of the `path` attribute, only in the `name` attribute. You must have changed your xml file by accident, or they got corrupted somehow.

**Comment by targetnull** [comment]
Yes, it is the `name` attribution rather than `path` attribution. I've modified my posts.
Sorry for the confusion it caused. 

But only after I deleted those `.git` did it begin to work. Anyway, the whole project is fetched now and I'm able to try the test suite finally.

Thank you for your help, Brand and vchong!
