### ISSUE TITLE
Hikey_debian different linux repos?

### ISSUE THREAD

**Issue by acarb95** [OP-TEE/manifest#64]
I was originally working off of OP-TEE 2.4.0 which used [this](https://github.com/linaro-swg/linux) linux repo. I just pulled down and started to build OP-TEE 2.5.0 but noticed the linux repo is different, it is now [rpk](https://github.com/Linaro/rpk). 

Upon further inspection, a lot of the client functions I was relying on are missing (client_open_session, etc.). But the rpk repo seems to be the one currently worked on (most recent commits). 

Is there a reason why these are not in the current linux repo? Which repo should I be using?

**Comment by vchong** [comment]
https://github.com/linaro-swg/linux is newer in terms of OP-TEE related patches, but is only a 'minimal' kernel that doesn't properly support debian. E.g. the mouse and keyboard and wifi(?) don't work.

https://github.com/Linaro/rpk is a 'debian' kernel. It lacks behind in terms of OP-TEE patches, but should still support the kernel internal client interface that you're using. How are they missing for you?
If you don't care about the 'debian-y' stuffs, feel free to swap back to https://github.com/linaro-swg/linux in 2.5.0 and rebuild, but if all you need is a command line to do TEE development, perhaps `hikey.xml` might be a better choice compared to `hikey_debian.xml`.

Both are 4.9.

**Comment by acarb95** [comment]
I need tee_client_open_context, tee_client_close_context, tee_client_open_session, tee_client_close_session, and tee_client_invoke_func in tee_core.c. I didn't see these in the rpk repository.

Unfortunately, debian is a hard requirement for the project, we need the desktop GUI as well as the applications that come with debian.

**Comment by vchong** [comment]
You're right, sorry. https://github.com/Linaro/rpk does not have the internal client interface patch. I was looking at my own branch. Not sure what the update policy is for Linaro/rpk. Will try to find out. In the meantime, you can use https://github.com/vchong/linux/tree/rpk-v4.9+optee-2e26af9.

**Comment by vchong** [comment]
I've sent an update to https://github.com/Linaro/rpk/pull/1. Not sure if they'll take it.

**Comment by jenswi-linaro** [comment]
@acarb95 I'm planning to post the "tee: add kernel internal client interface" patch on the kernel mailing list as a step in upstreaming it. Since there's (obviously) nothing in the kernel that uses that today it would help if people that uses the patch give that as feedback on the patch, ideally as a `Tested-by` tag. Other kind of feedback is also welcome of course.
Can I add you as CC to the patch when posting? Which email address can I use?

**Comment by acarb95** [comment]
Yes you can CC me, use the email: acarb95@cs.ubc.ca.

**Comment by jenswi-linaro** [comment]
@acarb95, thanks.
